samples/config/routes.rb
PermissionsSamples::Engine.routes.draw do
  match "permissions(/:action)",  :controller => "permissions", :as => :permissions
  root :to => "permissions#index"
end

samples/app/models/permissions_samples/api_form_builder.rb
module PermissionsSamples
  class APIFormBuilder < SimpleForm::FormBuilder
    def fields_for(member_name, member_object = nil, &block)
      member_object ||= ( object.send(member_name) || object.send("#{member_name}=", {}))
      member_options = object.class.members[member_name.to_sym]
      if member_options[:array]
        fields = []
        member_object.each_with_index do |obj, index|
          fields << super(member_name, obj, :index => index, &block)
        end
        fields.join.html_safe
      else
        super(member_name, member_object, &block)
      end
    end
    alias_method :simple_form_for, :fields_for
    alias_method :association, :fields_for

    def input(member_name, options = {})
      super(member_name, api_input_options(member_name, options))
    end

    def api_input_options(member_name, options = {})
      member_options      = object.class.members[member_name.to_sym]
      options[:label]   ||= member_name.to_s.underscore.humanize
      options[:wrapper] ||= :api_sample_form
      options[:required]  = !!member_options[:required] if options[:required].nil?
      if member_options[:type] < PayPal::SDK::Core::API::DataTypes::Enum
        options[:as] = ( member_options[:array] ? :check_boxes : :select )
        options[:collection] = member_options[:type].options
      elsif member_options[:type] == PayPal::SDK::Core::API::DataTypes::SimpleTypes::Boolean
        options[:as] = :select
        options[:collection] = [ true, false ]
      end
      options
    end
  end
end

samples/app/controllers/permissions_samples/application_controller.rb
module PermissionsSamples
  class ApplicationController < ActionController::Base

    def default_api_value
      t("#{service_name}.#{service_action}", :default => {})
    end

    def service_name
      params[:controller].gsub(/^.*\//, "")
    end

    def service_action
      params[:action]
    end
    helper_method :service_action, :service_name

  end
end

samples/app/controllers/permissions_samples/permissions_controller.rb
require_dependency "permissions_samples/application_controller"

module PermissionsSamples
  class PermissionsController < ApplicationController
    include PayPal::SDK::Permissions

    def index
      redirect_to :action => :request_permissions
    end

    def request_permissions
      @request_permissions = api.build_request_permissions(params[:RequestPermissionsRequest] || default_api_value)
      # Set default callback URL
      @request_permissions.callback ||= permissions_url(:get_access_token)
      @request_permissions_response = api.request_permissions(@request_permissions) if request.post?
    end

    def get_access_token
      @get_access_token = api.build_get_access_token(params[:GetAccessTokenRequest] || default_api_value)

      # To handle the return value from paypal
      @get_access_token.token     = params["request_token"]     if params["request_token"]
      @get_access_token.verifier  = params["verification_code"] if params["verification_code"]

      @get_access_token_response = api.get_access_token(@get_access_token) if request.post?
    end

    private

    def api
      @api ||= API.new
    end
  end
end

samples/app/helpers/permissions_samples/application_helper.rb
module PermissionsSamples
  module ApplicationHelper
    def active_li(display, link_path, options = {})
      active_menu = options.delete(:match_path) ? request.path =~ Regexp.new(link_path) : request.path == link_path
      content_tag(:li, :class => active_menu ? "active" : "") do
        link_to(display, link_path, options)
      end
    end

    def active_li_regexp(display, link_path, options = {})
      active_li(display, link_path, options.merge(:match_path => true))
    end

    def api_form_for(object, *args, &block)
      options         = args.extract_options!
      options[:as]  ||= api_class_name(object.class)
      simple_form_for(object, *(args << options.merge(:builder => APIFormBuilder, :wrapper => :api_sample_form)), &block)
    end

    def generate_code(api_request, api_response)
      request_hash= api_request.to_hash(:namespace => false, :attribute => false)
      request_hash.delete(:Version)
      # request_hash  = get_dotted_hash(request_hash)
      response_hash = api_response.to_hash(:namespace => false, :attribute => false)
      ruby_code   = render("ruby_code.rb", :api_request => api_request, :api_response => api_response,
                           :request_hash => request_hash, :response_hash => response_hash)
      ruby_code.html_safe
    end

    def get_dotted_hash(hash, prefix = "", values = {})
      max_lenght  = Hash[hash.select{|k, v| !(v.is_a? Hash or v.is_a? Array) }].keys.map(&:size).max
      hash.each do |key, value|
        if value.is_a? Hash
          get_dotted_hash(value, "#{prefix}#{key}.", values)
        elsif value.is_a? Array and value[0].is_a? Hash
          value.each_with_index do |array_value, index|
            get_dotted_hash(array_value, "#{prefix}#{key}[#{index}].", values)
          end
        elsif !value.nil?
          k = sprintf("%s%-#{max_lenght}s", prefix, key)
          values[k] = value
        end
      end
      values
    end

    def format_hash(hash)
      entries = hash.map do |key, value|
        "#{key.to_sym.inspect} => " +
          if value.is_a? Hash and value.size > 0
            format_hash(value)
          elsif value.is_a? Array and value[0].is_a? Hash
            "[" + value.map{|v| format_hash(v) }.join(",") + "]"
          else
            value.to_json
          end
      end
      indent_hash_entries(entries)
    end

    def indent_hash_entries(entries)
      if entries.size > 0
        "{\n" + entries.join(",\n").gsub(/^/, "  ") + " }"
      else
        "{}"
      end
    end

    def api_class_name(klass)
      klass.name.gsub(/^.*::/, "")
    end
  end
end

samples/app/helpers/permissions_samples/permissions_helper.rb
module PermissionsSamples
  module PermissionsHelper
  end
end

samples/app/views/layouts/permissions_samples/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "#{service_action.humanize} | #{service_name.humanize}"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag    "permissions_samples/application", :media => "all"
  %body
    = render "header"
    .container
      .row
        .span2= render "sidebar"
        .span10= yield
    = javascript_include_tag "permissions_samples/application"

samples/app/views/permissions_samples/application/_api_response.html.haml
%div#response
  %p
    %b Ruby Code:
    = find_and_preserve CodeRay.scan(generate_code(request, response), "ruby").div.html_safe
  %p
    %b Response:
    = find_and_preserve CodeRay.scan(format_hash(response.to_hash(:attribute => false, :namespace => false)), "ruby").div.html_safe

samples/app/views/permissions_samples/application/_hash_block.rb.erb
<% hash.each do |key, value| -%>
  <% if value.is_a? Hash -%>
<%= space %><%= key %> do
<%= render "hash_block.rb", :space => space + "  ", :hash => value %>
<%= space %>end
  <% elsif value.is_a? Array and value[0].is_a? Hash -%>
    <% value.each_with_index do |array_value, index| -%>
<%= space %><%= key %>[<%= index %>] do
<%= render "hash_block.rb", :space => space + "  ", :hash => array_value %>
<%= space %>end
    <% end -%>
  <% else -%>
<%= space %>self.<%= key %> = <%= value.to_json.html_safe %>
  <% end -%>
<% end -%>

samples/app/views/permissions_samples/application/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .pull-right
        = link_to "Source on GitHub", "https://github.com/paypal/permissions-sdk-ruby", :class => "btn btn-small"
        %span.btn.btn-info.btn-small.disabled Click Submit to Generate Code !
      %a.brand{:href => "#"} PayPal SDK
      .nav-collapse.collapse
        %ul.nav
          = active_li_regexp "Permissions", permissions_path

samples/app/views/permissions_samples/application/_ruby_code.rb.erb
require 'paypal-sdk-<%= service_name.gsub("_", "") %>'
@api = PayPal::SDK::<%= service_name.camelize %>::API.new

# Build request object
@<%= service_action %> = @api.build_<%= service_action %>(<%= format_hash(request_hash).html_safe %>)

# Make API call & get response
@<%= service_action %>_response = @api.<%= service_action %>(@<%= service_action %>)

# Access Response
if @<%= service_action %>_response.success?
<% api_response.members.keys.each do |name| -%>
  <% unless [:xmlns, :type, :responseEnvelope, :error].include? name -%>
  @<%= service_action %>_response.<%= name %>
  <% end %>
<% end -%>
else
  @<%= service_action %>_response.error
end

samples/app/views/permissions_samples/application/_sidebar.html.erb
<ul class="nav nav-list bs-docs-sidenav ">
  <%= active_li "Home",  "/" %>
</ul>

samples/app/views/permissions_samples/application/_token.html.haml
%legend Autherization
.control-group.string.optional
  = label_tag :token, "Token", :class => "string optional control-label"
  .controls
    = text_field_tag :token, params[:token] || @api.config.token

.control-group.string.optional
  = label_tag :token_secret, "Token Secret", :class => "string optional control-label"
  .controls
    = text_field_tag :token_secret, params[:token_secret] || @api.config.token_secret

samples/app/views/permissions_samples/permissions/_sidebar.html.haml
.well.well-mini
  %ul.nav.nav-list.bs-docs-sidenav
    = active_li "Request Permissions",  permissions_path(:request_permissions)
    = active_li "Get Access Token",     permissions_path(:get_access_token)

samples/app/views/permissions_samples/permissions/get_access_token.html.haml
= api_form_for @get_access_token, :url => permissions_path(:get_access_token) do |f|

  .row
    .span5
      %legend Get access token
      = f.input :verifier
      = f.input :token

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_access_token_response
  = render 'api_response', :request => @get_access_token, :response => @get_access_token_response

samples/app/views/permissions_samples/permissions/request_permissions.html.haml
= api_form_for @request_permissions, :url => permissions_path(:request_permissions) do |f|

  .row
    .span5
      %legend Request Permissions
      = f.input :callback
      = f.input :scope, :as => :check_boxes, :collection => [ "EXPRESS_CHECKOUT", "DIRECT_PAYMENT",
        "AUTH_CAPTURE", "AIR_TRAVEL", "ACCESS_BASIC_PERSONAL_DATA","ACCESS_ADVANCED_PERSONAL_DATA",
        "TRANSACTION_SEARCH", "RECURRING_PAYMENTS", "ACCOUNT_BALANCE", "ENCRYPTED_WEBSITE_PAYMENTS", "REFUND",
        "BILLING_AGREEMENT", "REFERENCE_TRANSACTION", "MASS_PAY", "TRANSACTION_DETAILS", "NON_REFERENCED_CREDIT",
        "SETTLEMENT_CONSOLIDATION", "SETTLEMENT_REPORTING", "BUTTON_MANAGER", "MANAGE_PENDING_TRANSACTION_STATUS",
        "RECURRING_PAYMENT_REPORT", "EXTENDED_PRO_PROCESSING_REPORT", "EXCEPTION_PROCESSING_REPORT",
        "ACCOUNT_MANAGEMENT_PERMISSION", "INVOICING" ]

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @request_permissions_response
  = render 'api_response', :request => @request_permissions, :response => @request_permissions_response

  %p
    %b Grant Permission
    = link_to "Follow the link to generate token", @api.grant_permission_url(@request_permissions_response)